# Generated by Django 4.2.10 on 2025-04-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutversion',
            name='version_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
