services:
  web:
    build: .
    command: gunicorn grid_layout.wsgi:application --bind 0.0.0.0:8000
    volumes:
     - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
volumes:
  static_volume: {}